return {}
-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--   opts = {
--     sources = {
--       null_ls.builtins.formatting.eslint_d,
--       null_ls.builtins.formatting.eslint_d.with({
--         filetypes = { "javascript", "typescript", "javascriptreact", "typescriptreact" },
--       }),
--     },
--   },
-- })
